### PR TITLE
Minimum Width, Larger Hit Size on Sidebar Splitter

### PR DESCRIPTION
**Pull request by robcee**
This PR addresses a couple usability annoyances I found.
1st, this sets a minimum width so users can't collapse the sidebar into an unhittable, unresizable, 0px unspace. I used 40px which keeps the favicon still visible.
2nd, added a 3px invisible hit region to the sidebar splitter so it's easier to grab. Stolen gratuitously from our devtools sidebar css.

Did some minor cleanup of osx.css. Restored vvuk to the Creator of this addon, changed the id to be reflective of what it is (and not who), and bumped the version number ever-so-slightly indicating it's forked, updated and much-improved status.

Oh yeah! Changed the Makefile to produce an XPI named "VerticalTabs.xpi" in the parent folder. This might be contentious since the release won't end up in the same directory, but version controlling zipped files in git seems kinda silly. When this eventually moves to AMO, we might prefer this as a build procedure.

Please accept me! <3

### CODE REVIEW

**Comment by seriousben** [comment]
:sweet_potato:

**Comment by robcee** [comment]
🐣

**Comment by darrinhenein** [comment]
Thanks Rob :)

**Comment by robcee** [comment]
Thank you for reinvigorating this! I have a couple of other things I want to try out around resizing.

**Pull request merged**
